### PR TITLE
Feature/46 primer with examples

### PR DESCRIPTION
**Pull request by pieroit**
Just a prototype of the primer mentioned in #46.
Pushing it as a PR in order to update content of the original repo instead of linking my fork... please leave suspended. :)

### CODE REVIEW

**Comment by l00mi** [comment]
@pieroit This looks good as a first draft, any plans to work on this a bit more?

**Comment by pieroit** [comment]
I was waiting for the spec to crystallize a little.
Yes I plan to go on ASAP ;)

**Comment by l00mi** [comment]
Good to hear!

**Comment by elf-pavlik** [comment]
For examples we should possibly reuse https://github.com/rdf-ext/rdf-examples

**Comment by l00mi** [comment]
@pieroit still any juice around for this one?

**Comment by pieroit** [comment]
Sorry, work is taking all the fun away. Hating capitalism every day more.

I wrote this some time ago:
https://pieroit.org/portfolio/linked-data-grandma/
But it's not specific on RDFJS

**Comment by elf-pavlik** [comment]
I think we can close this one and if someone wants to work on primer we could work on it in dedicated repo.

**Pull request closed without merging**
