### PR TITLE
Clarify that returned `Terms` are novel

### PR DESCRIPTION
**Pull request by ericprud**
for s a quad store with one triple,
## Triples are novel
``` javascript
s.getQuads()[0].equals(s.getQuads()[0]) // true
s.getQuads()[0] == s.getQuads()[0] // false
```
## Terms are novel
``` javascript
s.getQuads()[0].subject.equals(s.getQuads()[0].subject) // true
s.getQuads()[0].subject == s.getQuads()[0].subject // false
```

### CODE REVIEW

**Comment by ericprud** [comment]
The problem with "not obligated" is that it lures folks into writing incompatible code, i.e. they develop on some system where Term identity is preserved and that code doesn't work with other RDF JS stores. It's fine if they do that for performance or simplicity, but it should be very clear to them when they do that they are stepping outside RDF JS and sacrificing interop.

**Comment by RubenVerborgh** [comment]
I would rather add to the spec that equality checks with `==` or `===` are not supported; should always be `equals`.

**Comment by elf-pavlik** [comment]
@RubenVerborgh I see this PR adds that implementations *should* use `equals()` do you have specific way of rephrasing it you would prefer?

**Comment by RubenVerborgh** [comment]
Equality MUST only be checked with equals?

**Comment by ericprud** [comment]
I guess I brought us into 2119-land with the use of "should". I think we're not saying that you're not *allowed* to use `==`, just that it's not RDF JS if you do. How about changing the last sentence:?
``` diff
- Callers should use the `Term.equals()` function instead of `===` or `==` to test for equivalence.
+ Equivalence is tested with the `Term.equals()` function instead of `===` or `==`.
```

**Comment by RubenVerborgh** [comment]
👍

**Pull request merged**
