### PR TITLE
DataFactory methods to create from existing term and quad | closes #137

### LINKED ISSUE #137: Add DataFactory method to create from existing term
We want to consider adding a method to `DataFactory` that takes a `Term`-shaped object (from _any_ library) as input, and outputs a `Term` (from the library of the `DataFactory`) that `equals` it.

This can be used to convert a `Term` from one RDF/JS implementation to another.

### PR DESCRIPTION
**Pull request by elf-pavlik**
As discussed in #137

### CODE REVIEW

**Comment by elf-pavlik** [comment]
:wave:

**Comment by blake-regalia** [comment]
I'm pretty sure that with #142 we could simply say, such that `newObject.equals(original)` as this would cover all cases including *plain objects*, correct?

**Comment by elf-pavlik** [comment]
Can we do it the other way and require that newly created instance will have `.equals()` method and passing `original` to it returns `true` ? Since it looks like spec will include definition of `.equals()` #150 I think that `fromTerm` and `fromQuad` definitions should simply take advantage of already eisting definition of `.equals()`

**Comment by blake-regalia** [comment]
@elf-pavlik I think that is exactly what I am proposing... do we have a misunderstanding?

**Comment by elf-pavlik** [comment]
Thanks for commit @blake-regalia :+1: 
No misunderstanding, just race condition on github comments :racehorse:

**Comment by elf-pavlik** [comment]
@dmitrizagidulin I noticed you had some suggestions in https://github.com/rdfjs/data-model-spec/issues/81#issuecomment-239825876 would you like to review this PR?

**Pull request merged**
